### PR TITLE
chore: bumped intl package version

### PR DESCRIPTION
**Pull request by frarcos**

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
Can you elaborate more on why that is needed? 

^ allows 0.17 and 0.18 and 0.19 and any non major version update so having a bigger version pool is easier for users don't you think?

**Comment by frarcos** [comment]
As I'm aware the package is not compatible with the project using ^0.19 intl dependency.
```
Because my_package depends on ftp_server from path which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because my_package depends on intl ^0.19.0, version solving failed.
```

**Comment by abdelaziz-mahdy** [comment]
Oh okay, will do the upgrade, thank you

**Comment by abdelaziz-mahdy** [comment]
0.0.7 released, thank you for your contribution.

**Pull request merged**
