### PR TITLE
Virtual dir

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
removes old files operations to replace it with new class that makes a virtual file system and allows access to only allowed dirs

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
@lawnvi do you think you can check these new changes, it allows more control over dirs now you can share more than one dir instead of the one dir and uses path package to normalise stuff, if you have a case not covered let me know

**Comment by lawnvi** [comment]
> @lawnvi do you think you can check these new changes, it allows more control over dirs now you can share more than one dir instead of the one dir and uses path package to normalise stuff, if you have a case not covered let me know

Apologies for the delay in getting back to you. I just saw your message and will try out the changes as soon as possible. If I encounter any issues, I’ll let you know.

**Comment by lawnvi** [comment]
image
windows ftp client seems to not support the SIZE command.

**Comment by abdelaziz-mahdy** [comment]
Thank you for your work, what do you think about the changes 


I think using the path module is a cleaner approach and having the ability to share more than one dir is the original need for ftp 

Do you have anymore ideas or missing features that needs to be added?

**Comment by lawnvi** [comment]
Selecting multiple files at once is indeed very useful, as the files you want to share are not always in the same directory.

In macOS Finder, some operations related to the server, such as renaming, deleting, and uploading files (drag and drop or paste), may not be displayed.

Additionally, characters like ‘|’ might be supported on one platform but not on another, which can lead to problems.

image

**Comment by abdelaziz-mahdy** [comment]
In macOS Finder, some operations related to the server, such as renaming, deleting, and uploading files (drag and drop or paste), may not be displayed. , i didnt try to connect to ftp server using finder, should it show these options? if thats the case will need to check what commands need to added, 

edit: i cant find the needed commands :_( 

and for | i think there is a need to replace all the special chars to be safe on all platforms

**Pull request merged**
